name: Publish to npm
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - 'fix-build*'

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build Userflow.js
        run: npm run build
      - name: Publish
        run: npm publish
